
services:
  flask:
    build:
      context: ./flask_app
    container_name: flask_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./flask_app:/app
      - ./flask_app/templates:/app/templates
    networks:
      - mynetwork
    command: ["/wait-for-it.sh", "mysql:3306", "--", "python", "app.py"]

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "/c/Users/liani/devops-1144-git/RL/devops-project/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
