services:
  flask:
    build: .
    container_name: flask_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./flask_app:/app   # תיקיית ה-Flask שלך
      - ./flask_app/templates:/app/templates   # תיקיית ה-templates של Flask
    networks:
      - mynetwork

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
