replicaCount: 2

image:
  repository: romliani/devops-project-flask
  tag: latest
  pullPolicy: Always

service:
  port: 5000

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

volumeMounts: []

volumes: []

nodeSelector: {}

affinity: {}

tolerations: []
