version: '3'
services:
  web:
    build: ./flask
    environment:
      - DATABASE_URL=mysql://root:example@db:3306/gif_db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gif_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
