version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gifs
    restart: always
    env_file: .env
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  flask_app:
    build: .
    container_name: flask_gifs
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

volumes:
  mysql_data:
