CREATE DATABASE IF NOT EXISTS gifs_db;

USE gifs_db;

CREATE TABLE IF NOT EXISTS gifs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
