---
name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: |
        docker pull romliani/devops-project-flask:latest

    - name: Run Docker container for testing
      run: |
        docker run -d -p 5000:5000 --name flask_test romliani/devops-project-flask:latest
        sleep 10 # Wait for the container to initialize
        curl -s http://localhost:5000
