apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app  # שים לב לשם דינמי לפי השם של ה־release
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}  # דינמי - תואם ל־Service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}  # גם כאן אותו דבר
    spec:
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
