name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform init and apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.GKE_SA_KEY }}" | base64 --decode > /tmp/gke-key.json
          gcloud auth activate-service-account --key-file=/tmp/gke-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone --project ${{ secrets.GCP_PROJECT_ID }}

          # Apply Kubernetes manifests
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
