name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover tests

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Terraform init and apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Deploy to Kubernetes
        run: |
          # Set up kubectl and authenticate with your Kubernetes cluster
          echo "${{ secrets.GKE_SA_KEY }}" | base64 --decode > /tmp/gke-key.json
          gcloud auth activate-service-account --key-file=/tmp/gke-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone --project ${{ secrets.GCP_PROJECT_ID }}

          # Apply Kubernetes manifests
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
