---
### ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Cache Terraform dependencies
        uses: actions/cache@v3
        with:
          path: devops-project/terraform/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('devops-project/terraform/terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init
        working-directory: devops-project/terraform

      - name: Terraform Plan
        run: terraform plan -parallelism=10
        working-directory: devops-project/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -parallelism=10
        working-directory: devops-project/terraform

  docker:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build --cache-from=type=gha --cache-to=type=gha,mode=max \
          -t romliani/devops-project-flask:latest -f devops-project/flask_app/Dockerfile devops-project/flask_app/
          docker push romliani/devops-project-flask:latest
