---
name: Build Docker Image and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List root files for debugging
      run: ls -la

    - name: List files in devops-project folder
      run: ls -la devops-project

    - name: List files in flask_app folder
      run: ls -la devops-project/flask_app/

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r devops-project/flask_app/requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s devops-project/flask_app/tests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t romliani/devops-project-flask:latest -f devops-project/flask_app/Dockerfile devops-project/flask_app/

    - name: Clean up old Docker images
      run: |
        docker image prune -f --filter "until=120h"

    - name: Push Docker image
      run: |
        docker push romliani/devops-project-flask:latest