name: Docker Cleanup

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Get DockerHub Token
      run: |
        RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" \
          -d "{\"username\": \"${{ secrets.DOCKER_USERNAME }}\", \"password\": \"${{ secrets.DOCKER_PASSWORD }}\"}" \
          https://hub.docker.com/v2/users/login/)
        echo "Response: $RESPONSE"
        TOKEN=$(echo $RESPONSE | jq -r .token)

        if [ "$TOKEN" == "null" ]; then
          echo "Error: Unable to fetch token from Docker Hub"
          exit 1
        fi

    - name: List Docker images and delete old ones
      run: |
        REPO="romliani/devops-project-flask"  # שם הרפוזיטורי שלך ב-Docker Hub
        
        # קבלת רשימת התגים (tags) מה-DockerHub
        IMAGES=$(curl -s -H "Authorization: Bearer $TOKEN" \
          "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" | jq -r '.results | map(select(.name != "latest")) | .[].name')

        if [ -z "$IMAGES" ]; then
          echo "Error: No images found or unable to fetch images"
          exit 1
        fi

        # שמירת 3 הגרסאות האחרונות בלבד
        KEEP_IMAGES=$(echo "$IMAGES" | head -n 3)

        # עבור כל תמונה (tag) ברשימה
        for IMAGE in $IMAGES; do
          if echo "$KEEP_IMAGES" | grep -q "$IMAGE"; then
            echo "Keeping image: $IMAGE"
          else
            # קבלת ה-digest של התמונה
            DIGEST=$(curl -s -H "Authorization: Bearer $TOKEN" \
              "https://hub.docker.com/v2/repositories/$REPO/tags/$IMAGE/" | jq -r '.digest')

            if [ "$DIGEST" == "null" ]; then
              echo "Error: Unable to fetch digest for image $IMAGE"
              exit 1
            fi

            echo "Deleting old image: $IMAGE (digest: $DIGEST)"
            curl -X DELETE -H "Authorization: Bearer $TOKEN" \
              "https://hub.docker.com/v2/repositories/$REPO/manifests/$DIGEST/"
          fi
        done
