name: Docker Cleanup

on:
  schedule:
    - cron: '0 0 * * 1' # ירוץ פעם בשבוע ביום שני
  workflow_dispatch:  # הוספת האפשרות להריץ ידנית

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Remove old Docker images locally
        run: docker image prune -af  # מוחק תמונות שלא בשימוש

      - name: Delete old images from DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"username\": \"$DOCKERHUB_USERNAME\", \"password\": \"$DOCKERHUB_PASSWORD\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)

          REPO="romliani/devops-project-flask"

          IMAGES=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" | jq -r '.results | map(select(.name != "latest")) | .[].name')

          # שמירת 3 הגרסאות האחרונות בלבד
          KEEP_IMAGES=$(echo "$IMAGES" | head -n 3)

          for IMAGE in $IMAGES; do
            if echo "$KEEP_IMAGES" | grep -q "$IMAGE"; then
              echo "Keeping image: $IMAGE"
            else
              DIGEST=$(curl -s -H "Authorization: Bearer $TOKEN" \
                "https://hub.docker.com/v2/repositories/$REPO/tags/$IMAGE/" | jq -r '.digest')

              if [ "$DIGEST" != "null" ]; then
                echo "Deleting old image: $IMAGE (digest: $DIGEST)"
                curl -X DELETE -H "Authorization: Bearer $TOKEN" \
                  "https://hub.docker.com/v2/repositories/$REPO/manifests/$DIGEST/"
              fi
            fi
          done
