name: Deploy with Helm

on:
  workflow_run:
    workflows: ["Terraform Plan and Apply"]
    types:
      - completed

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1

    # Add Helm chart repository
    - name: Add Helm chart repository
      run: |
        helm repo add my-repo https://charts.example.com
        helm repo update

    # Install or upgrade Helm release
    - name: Install or upgrade Helm release
      run: |
        helm upgrade --install flask-app ./devops-project/mychart/flask-chart \
          --set image.repository=romliani/devops-project-flask \
          --set image.tag=latest
