name: Helm Deploy

on:
  workflow_run:
    workflows: ["Deploy Docker Image"]
    types:
      - completed

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials devops-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install GKE Auth Plugin
      run: |
        curl https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz | tar xz
        ./google-cloud-sdk/install.sh --quiet
        ./google-cloud-sdk/bin/gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-app ./mychart/flask-chart
