name: Helm Deployment

on:
  workflow_run:
    workflows: ["Terraform Deployment"]  # אחרי שה-Terraform הסתיים
    types:
      - completed

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Add Helm Chart Repository
      run: helm repo add stable https://charts.helm.sh/stable

    - name: Install Helm Chart
      run: helm upgrade --install flask-app ./flask-chart --namespace default
