name: Helm Deploy

on:
  workflow_run:
    workflows: ["Deploy Docker Image"]
    types:
      - completed

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | gcloud auth activate-service-account --key-file=-
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials devops-cluster --region us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy with Helm
      run: |
        helm upgrade --install flask-app ./mychart/flask-chart
