name: Deploy with Helm

on:
  workflow_run:
    workflows: ["Terraform Plan and Apply"]  # ירוץ לאחר סיום ה-Terraform
    types:
      - completed

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # 3. Add Helm chart repository (אם אתה עובד עם chart public או פרטי)
    - name: Add Helm chart repository
      run: helm repo add my-repo https://charts.example.com

    # 4. Install/Upgrade Helm release
    - name: Install or upgrade Helm release
      run: |
        helm upgrade --install flask-app ./devops-project/mychart/flask-chart \
          --set image.repository=romliani/devops-project-flask \
          --set image.tag=latest
