name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.4.0"

    - name: Configure GCP credentials
      uses: google-github-actions/setup-gcloud@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # הוסף את המפתח החיוני של GCP ב-Secrets

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
