name: Terraform Plan and Apply

on:
  workflow_run:
    workflows: ["Build Docker Image and Push to Docker Hub"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }} # כאן אנחנו מעבירים את ה-secrets

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.5.0'

    - name: Terraform Init
      run: terraform init
      working-directory: ./devops-project/terraform

    - name: Run Terraform Plan
      run: terraform plan
      working-directory: ./devops-project/terraform

    - name: Apply Terraform Plan
      run: terraform apply -auto-approve
      working-directory: ./devops-project/terraform
      if: github.event_name == 'workflow_run'
